Jenkinsfile

pipeline {
	agent any
	stages {
	    stage ('Pull') {
			steps {
				git 'https://github.com/Danletski/Gollum.git'
			}
		}
		stage ('Deploy Vagrant') {
			steps {
				sh 'sudo vagrant plugin install vagrant-docker-compose'
				sh 'sudo vagrant --verbose up -d'
			}
	
		}
		stage ('Test') {
			steps {
				sh 'vagrant ssh'
				sh 'cd /etc/ansible/'
			        sh 'sudo chmod +x testall.py'
				sh 'sudo python testall.py'
			}
		}
		stage ('Stop') {
		    steps {
		        sh 'exit'
		        sh 'vagrant destroy -y'
		    }
		}
	}
}
