Vagrant.configure("2") do |config|
  config.vm.box = "minimal/xenial64"
  config.vm.synced_folder "./", "/etc/ansible"
  config.vagrant.plugins = "vagrant-docker-compose"
  config.vm.provision :docker
  system("vagrant plugin install vagrant-docker-compose")
  config.vm.provision :docker_compose, yml: "/etc/ansible/docker-compose.yml", rebuild: true, run: "always"
  config.vm.network "public_network", 
    use_dhcp_assigned_default_route: true
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
   config.vm.provision "shell", inline: <<-SHELL
     apt-get install -y software-properties-common
     apt-add-repository ppa:ansible/ansible
     apt-get update
     apt-get install -y ansible
   SHELL
  end

