Vagrant.configure("2") do |config|
  config.vm.box = "minimum/ubuntu-trusty64-docker"
  config.vm.synced_folder "./", "/etc/ansible"
  config.vm.network "public_network", 
    use_dhcp_assigned_default_route: true
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
   config.vm.provision "shell", inline: <<-SHELL
     apt-get install -y software-properties-common
     apt-add-repository ppa:ansible/ansible
     apt-get update
     apt-get install -y ansible
     sudo dpkg --configure -a
   SHELL
  end

